# dbt_project.yml

name: 'clan_analytics_dbt'
version: '1.0.0'
config-version: 2

profile: 'clan_analytics_dbt' # This should match the profile you configured during dbt init

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to clean out on `dbt clean`
  - "target"
  - "dbt_packages"


models:
  clan_analytics_dbt:
    staging:
      +schema: staging
      +materialized: view
    marts:
      +schema: analytics
      +materialized: table
